### ISSUE TITLE
Websites to try

### ISSUE THREAD

**Issue by DaveAldon** [DavidAldon/Feed-Kelso#1]
https://github.com/ebidel/polymer-gmail

https://www.pubnub.com/blog/2015-01-15-creating-a-polymer-chat-app-with-material-design/

https://github.com/google/santa-tracker-web

**Comment by QuestionableSaint** [comment]
Do we want to work with polymer then?

**Comment by DaveAldon** [comment]
Or Apache Cordova if we go the tinder clone route

**Comment by DaveAldon** [comment]
This tutorial is amazing and I have a working app running in a simulator currently

https://ccoenraets.github.io/cordova-tutorial/index.html

Working on getting another sample project working...

**Comment by DaveAldon** [comment]
Look at this....this is hilarious...

https://software.intel.com/en-us/html5/hub/blogs/how-to-make-a-mobile-virtual-pet-game-with-html5-and-cordova/

**Comment by kgriff12** [comment]
That last one is pretty cool haha

**Comment by DaveAldon** [comment]
They both work correctly, so we could currently do something with the puzzle or the pet thing
