### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by DaveAldon** [DavidAldon/Feed-Kelso#2]
Resources need to be changed which revolves around all of the graphics/sprites.

**Comment by DaveAldon** [comment]
https://github.com/DavidAldon/Feed-Kelso/commit/43b54aa145db32658c5f23a1c40bad8b52b8e51a

Added pictures that should probably be smaller at some point. We may not have to use the sprite idea, but individual photos for Kelso.

**Comment by DaveAldon** [comment]
This task should probably also involve CSS or some visual aspect of making everything pretty and not lame. For example, the high score board could look really cool and highlight your username. Currently I'm just setting the value of the list items to score + username, so if you'd like it passed to the HTML a different way let me know.

**Comment by kgriff12** [comment]
Added CSS to the leaderboard and register text. Highlighted the leaderboard for the current player to be displayed as green when in the Top Ranks.
