### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by DaveAldon** [DavidAldon/Feed-Kelso#3]
Game needs to keep the feeding, but I suggest changing fun to "Class Lateness" or something similar. Items should reflect the fact that Kelso needs to have them in order to "not be late."

Idea: Lateness starts at 0:00 and goes up. When it reaches 50 minutes, you lose.

Hunger should increase much faster in order to make the game a challenge.

**Comment by QuestionableSaint** [comment]
To increase difficulty over time we can make the 'hunger' meter start by slowly decreasing than speed up its rate of decline over time played during any particular game.

**Comment by DaveAldon** [comment]
I've separated the js files so that the firebase stuff won't have any merge issues with whatever you'd like to do to the game logic. So far the only variable from main.js I use is score, but that's just hunger. You'll need to come up with a universal score of some sort and then I'll reference that to dump into firebase.

Also, you might find my gameAwake bool concept in networking.js useful, which becomes true after a user registers, activating the firebase dumps. If you can find a way to "pause" the game until the player is ready that'd be a great feature so that they're not thrown into it immediately.

**Comment by QuestionableSaint** [comment]
I've been working on this for a while so I'll put it down:
I've gotten the game to pause. But. . .it doesn't unpause. 
The input event listener which is supposed to call the unpause event doesn't work, and I do believe it's a difference in syntax but because all the sources I've found use an entirely different syntax for phaser it's difficult to know exactly how to fix it. That line of code is simply:
game.input.onDown.add(unpause, self);

**Comment by DaveAldon** [comment]
That's a tough one. It looks like a custom pause function would need to be designed to work properly. Perhaps for a workaround you could just not load the html call to main.js until after the player successfully registers. As an additional idea, after the player loses for the first time, the update function could be modified to check if they want to play again like so, to stop it from auto-restarting:

`update: function() {`
**if(PressedRestartButton) {**
`    score = this.pet.customParams.health;`
`    if(this.pet.customParams.health <= 0 || this.pet.customParams.fun <= 0) {`
`      this.pet.customParams.health = 0;`
`      this.pet.customParams.fun = 0;`
`      this.pet.frame = 4;`
`      this.uiBlocked = true;`
`      this.game.time.events.add(2000, this.gameOver, this);`
`    }`
**}**
`//And then deactivate it immediately for the next round to work`
**PressedRestartButton = !PressedRestartButton;**
`  },`
